name: ✨ Feature Request (Detailed)
description: Request a new feature
labels: ["enhancement"]
body:
  - type: markdown
    attributes:
      value: |
        ## ✨ Feature Request
        
        Describe the feature you'd like to see.

  - type: textarea
    id: feature
    attributes:
      label: Feature Description
      description: What would you like to see added?
      placeholder: |
        **What:**
        
        **Why:**
        
        **Who benefits:**
    validations:
      required: true

  - type: textarea
    id: acceptance
    attributes:
      label: Acceptance Criteria
      description: What conditions must be met?
      placeholder: |
        - [ ] Criterion 1
        - [ ] Criterion 2
        - [ ] Criterion 3
    validations:
      required: true

  - type: dropdown
    id: components
    attributes:
      label: Affected Components
      multiple: true
      options:
        - Frontend (Svelte 5)
        - Backend (Rust)
        - Database (SQLite)
        - AI Integration
        - Documentation
        - Build/CI
    validations:
      required: false

  - type: dropdown
    id: complexity
    attributes:
      label: Estimated Complexity
      options:
        - 🟢 Low - Small change, minimal risk
        - 🟡 Medium - Moderate change, some risk
        - 🔴 High - Large change, significant risk
    validations:
      required: true

  - type: textarea
    id: context
    attributes:
      label: Additional Context
      description: Any related issues, mockups, or examples?
      placeholder: |
        Related issues: muicci/caliper-hq#X
        Mockups: <attach or link>
    validations:
      required: false
